### ISSUE TITLE
Vim 8.2.0235 fails to compile for macos

### ISSUE THREAD

**Issue by kristijanhusak** [rhysd/action-setup-vim#10]
Hi,

I started getting compiling failures for macos for Vim v8.2.0235. Here's an example build: https://github.com/kristijanhusak/vim-dadbod-ui/actions/runs/335558319.

There's also an issue #9 in the build.

**Comment by rhysd** [comment]
That's known issue of older Vim with the latest Xcode. Using Xcode 11 will solve the issue.

**Comment by rhysd** [comment]
> There's also an issue #9 in the build.

Nightly is unstable because it's built at HEAD of Neovim. Even if building Neovim when no nightly build asset is found, it will also fail since no asset found means build failure on Neovim CI.
