### ISSUE TITLE
Less verbose unzip on Windows if not RUNNER_DEBUG

### ISSUE THREAD

**Issue by williamboman** [rhysd/action-setup-vim#25]
Hey, thanks for this great action! I've noticed that the output on Windows is pretty verbose, due to it including the output of unpacking the archive. In my workflows, this usually ends up taking up ~95%+ of log output, which adds a lot of noise. I think it'd be nice if unpacking was done silently if `RUNNER_DEBUG` is not `1`.

I'm unable to check the source code at this very moment, but I believe this is already done on Unix systems? I remember looking into this a couple of months ago, but I came to the conclusion that it would require more changes than I anticipated - so I'm creating this issue as a starting point instead!

**Comment by rhysd** [comment]
I guess the log is output by this command: https://github.com/rhysd/action-setup-vim/blob/a4a511b08b77a6d0c52157264bf70ef8fa0a3d6c/src/vim.ts#L166

**Comment by rhysd** [comment]
0a4ca52 added `-q` to `zip` command execution when `RUNNER_DEBUG` is not set.

**Comment by williamboman** [comment]
Awesome!
