### ISSUE TITLE
Action hangs for Windows.

### ISSUE THREAD

**Issue by ubaldot** [rhysd/action-setup-vim#35]
I have the following in my workflow:

      - name: Run Tests
        run: |
          systeminfo
          echo "Vim command setup."
          $VIMPRG=${{ steps.vim.outputs.executable }}
          & $VIMPRG --version
          cd test
          echo "Done!"

But it seems that ´& $VIMPRG --version` is never executed. 
I get the following message:

```
Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal
```

and the run run indefinitely while being stuck at the two lines above.

**Comment by rhysd** [comment]
It may be related to PowerShell. How about running it with Bash?

```yaml
  - name: Run Tests
    shell: bash
    run: |
      systeminfo
      echo "Vim command setup."
      $VIMPRG=${{ steps.vim.outputs.executable }}
      & $VIMPRG --version
      cd test
      echo "Done!"
```

**Comment by rhysd** [comment]
If you intend to run GUI version, please try `gvim` instead of `${{ steps.vim.outputs.executable }}`.

**Comment by ubaldot** [comment]
With bash it works (sorry I forgot to mention). The only problem seems to be with Windows - I would like to test my stuff if it works on windows as well :)

**Comment by rhysd** [comment]
`shell: bash` works on Windows as well. Is there any reason to use PowerShell?

**Comment by ubaldot** [comment]
The reason is - I may be wrong - that people will use the plugins I am developing with Windows powershell/cmd.exe and I want to be 100% that the tests are run in a powershell Windows environment. Make sense? :)

**Comment by rhysd** [comment]
Yes, it makes sense :+1:

I looked your snippet closer and noticed that your environment variable syntax looks wrong to me.

Maybe is the following correct?

```yaml
  - name: Run Tests
    run: |
      systeminfo
      echo "Vim command setup."
      $Env:VIMPRG = "${{ steps.vim.outputs.executable }}"
      & $Env:VIMPRG --version
      cd test
      echo "Done!"
```

**Comment by ubaldot** [comment]
Thanks!
