### ISSUE TITLE
Building Vim on `macos-latest` fails due to lack of terminal library

### ISSUE THREAD

**Issue by rhysd** [rhysd/action-setup-vim#38]
https://github.com/rhysd/action-setup-vim/actions/runs/10131649545/job/28014627679

```
checking for tgetent()... configure: error: NOT FOUND!
      You need to install a terminal library; for example ncurses.
      Or specify the name of the library with --with-tlib.
```

**Comment by rhysd** [comment]
This build error was caused by building an older Vim v8.2.1931. Once I updated the version to v9.1.0626, this error no longer occurred. So the latest Vim happily finds ncurses on the latest macOS and there is no problem. I'm closing this ticket until someone really faces this issue since the build support for older version of Vim is a cost.

**Comment by lambdalisue** [comment]
I manually found the version where compilation becomes possible on macOS using a binary search. It would be great if a warning message could be added to avoid having to go through the same painful binary search process from version 8.2 to 9.1 again, lol.

![CleanShot 2024-10-15 at 02 42 39](https://github.com/user-attachments/assets/462b2f99-c0d3-4bec-a4aa-118faf44c4ef)

https://github.com/vim/vim/commit/0f0d3a7fb6473760b6f6679e3c8a81376220c869

**Comment by rhysd** [comment]
@lambdalisue I apologize for missing your comment. (Comments on closed issues are not notified to me unless I am mentioned.) I added a warning when the build fails for Vim older than 8.2.5134. Thank you!
